### ISSUE TITLE
Email report

### ISSUE THREAD

**Issue by aavram93** [Askedio/jquery-bootstrap-feedback#1]
You have a big problem with source of report.php

I'm try to make source and can create only without image. If you can develope my source, you're the best!
<?php
sleep(2);
// Define some variables
$to = 'webmaster@*******';
$subject = 'Test email';
// Create a boundary string. It must be unique so we use the MD5 algorithm to generate a random hash
$random_hash = md5(date('r', time()));

$ss = $_POST['screenshot'];
// Define the headers
$headers = "From: webmaster@*********_\r\n";
$headers = "Cc:webmaster@**_******\r\n";
// Add boundary string and mime type specification
$headers .= "Content-Type: multipart/mixed; boundary=\"PHP-mixed-".$random_hash."\"";
$headers .= "MIME-Version: 1.0\r\n";

// Read the attachment file contents into a string, encode it with MIME base64, and split it into smaller chunks
$attachment = chunk_split(file_get_contents($ss));

// Define the body of the message
$message = "
--PHP-mixed-$random_hash
Content-Type: text/html; charset='iso-8859-1'

".$_POST['comment']."
<img src='$ss' alt='SS'>

--PHP-mixed-$random_hash
Content-Type: image/png; name=imagine.png
Content-Transfer-Encoding: base64
Content-Disposition: attachment

$attachment
--PHP-mixed-$random_hash--";

// Send the email
mail($to, $subject, $message, $headers);
echo json_encode(array('result' => 'success'));

**Comment by gcphost** [comment]
Hi
I provided a new report.php that can provide the image as a file so you can mail it - how to mail you ask? well using phps mail() to send files isn't so friendly -  you can use php.net to find out how-to do that - or if you're not using a framework you should install phpmailer, it'll make it much easier.
