### ISSUE TITLE
Picture doesn't post/save

### ISSUE THREAD

**Issue by p08dev** [Askedio/jquery-bootstrap-feedback#2]
I tried to implement this button to a new site im working on and it works just fine except the image won't save. i have `if($screenshot) unlink($screenshot);` commented out and i didn't change the code, except that i put all the needed lines in my index.php. The picture is taken and put in the input field, but the php-script seems to don't work. I tried to put a example string in the `$screenshot` variable and it saved the image. 
My PHP version is 5.4.45-0+deb7u5.
Hope someone can help me.

**Comment by Furentes** [comment]
Never mind. Im retarded...

**Comment by p08dev** [comment]
Well... suddenly it works.
